import { defineConfig, type Plugin } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'node:fs'
import path from 'node:path'

// Serves /data (generated by generate.py) in dev and copies it into dist on build,
// so the synthetic data stays at the repo root as the PRD specifies.
function netraStaticData(): Plugin {
  const dataDir = path.resolve(__dirname, 'data')
  return {
    name: 'nicc-static-data',
    configureServer(server) {
      server.middlewares.use('/data', (req, res, next) => {
        const file = path.join(dataDir, decodeURIComponent((req.url || '').split('?')[0]))
        if (!file.startsWith(dataDir) || !fs.existsSync(file) || fs.statSync(file).isDirectory()) return next()
        res.setHeader('Content-Type', 'application/json')
        fs.createReadStream(file).pipe(res)
      })
    },
    closeBundle() {
      const out = path.resolve(__dirname, 'dist', 'data')
      fs.cpSync(dataDir, out, { recursive: true, filter: (src) => !src.includes('.cache') })
    },
  }
}

export default defineConfig({
  plugins: [react(), netraStaticData()],
  resolve: { alias: { '@': path.resolve(__dirname, 'src') } },
  build: { chunkSizeWarningLimit: 2000 },
})
