import { useEffect, useState } from 'react'
import { db } from '@/data/db'
import type { FailureClass, Incident, InterventionClass, Policy } from '@/data/types'
import type { PlanDraft } from '@/lib/plan'

// ---- Phase 1 data (p1_planner.json, generated by generate.py §15b) --------------------------
export interface P1Feature {
  id: string
  label: string
  unit: string
  source: string
  window: string
  definition: string
  direction: 1 | -1
  importance: number
  pop_p50: number
  pop_p90: number
}
export interface P1Site {
  site_id: string
  failure_class: FailureClass
  p8: number
  values: Record<string, number>
  contrib: Record<string, number> // probability points; sum + base rate = p8
  runs: number[] // p(W+8) on the last 9 weekly runs, oldest first, last = today
  first_flagged_run: number | null
  ci90: [number, number]
}
export interface P1Model {
  failure_class: FailureClass
  wave: number
  horizon: string
  precision_top_decile: number
  recall: number
  false_positive_rate: number
  override_rate: number
  drift_psi: number
  status: string
  backtest_months: number
  base_rate: number
  algorithm: string
  label: string
  training_window: string
  features: number
  versions: { version: string; date: string; note: string }[]
  current_version: string
  pr_curve: { recall: number; precision: number }[]
  calibration: { bin: string; predicted: number; observed: number; n: number }[]
  lift_by_decile: number[]
  precision_monthly: { month: string; precision: number }[]
  confusion_at_threshold: { threshold: number; tp: number; fp: number; fn: number; tn: number; population?: string }
  precision_metric?: string
  alert_share?: number
  retrain: string
  owner: string
}
export interface P1Data {
  as_of: string
  freshness: string
  run_dates: string[]
  feature_catalog: Record<FailureClass, P1Feature[]>
  base_rate: Record<FailureClass, number>
  sites: P1Site[]
  models: P1Model[]
  bySite: Map<string, P1Site>
}

let cache: P1Data | null = null
let pending: Promise<P1Data> | null = null

export function loadP1(): Promise<P1Data> {
  if (cache) return Promise.resolve(cache)
  if (!pending)
    pending = fetch('/data/p1_planner.json')
      .then((r) => r.json())
      .then((d: Omit<P1Data, 'bySite'>) => {
        cache = { ...d, bySite: new Map(d.sites.map((s) => [s.site_id, s])) }
        return cache
      })
  return pending
}

/** Phase 1 data hook. Returns null until loaded (pages show a skeleton). */
export function useP1(): P1Data | null {
  const [d, setD] = useState<P1Data | null>(cache)
  useEffect(() => {
    if (!d) loadP1().then(setD)
  }, [d])
  return d
}

// ---- Classes ------------------------------------------------------------------------------
export const CLASSES: FailureClass[] = ['capacity', 'power', 'transport', 'ran_hardware', 'environmental']
export const CLASS_META: Record<FailureClass, { label: string; short: string; color: string; defaultIntervention: string; owner: string; horizon: string; wave: number }> = {
  capacity: { label: 'Capacity', short: 'CAP', color: '#5AA9E6', defaultIntervention: 'sector_add', owner: 'PLAN', horizon: '8–12 weeks', wave: 1 },
  power: { label: 'Power', short: 'PWR', color: '#F5A623', defaultIntervention: 'power', owner: 'OPS', horizon: '4–6 weeks', wave: 1 },
  transport: { label: 'Transport', short: 'TRN', color: '#8B5CF6', defaultIntervention: 'transport', owner: 'OPS', horizon: '4–8 weeks', wave: 2 },
  ran_hardware: { label: 'RAN hardware', short: 'RAN', color: '#E4572E', defaultIntervention: 'ran_swap', owner: 'OPS', horizon: '6–8 weeks', wave: 2 },
  environmental: { label: 'Environmental', short: 'ENV', color: '#2ECC71', defaultIntervention: 'flood', owner: 'OPS', horizon: '2–4 weeks', wave: 3 },
}

// ---- Forecast clusters ---------------------------------------------------------------------
// Forecast Orchestrator output: one cluster per root cause. In this prototype the clusters
// are the predicted incidents from the base data, relabelled CL-.
export interface Cluster {
  id: string
  incident_id: string
  title: string
  cls: FailureClass
  site_ids: string[]
  province_id: string
  district_id: string
  region: string
  probability: number
  crossing_week: number
  exposure_idr: number
  priority: number
  coverage: Incident['program_match']
  recommended_rank: number
  story?: string
  days_to_breach?: number
}

export function clusterId(incidentId: string): string {
  return incidentId.replace('INC-', 'CL-')
}

export function clustersFrom(incidents: Incident[]): Cluster[] {
  return incidents
    .filter((x) => x.source === 'prediction' && (CLASSES as string[]).includes(x.class) && !['Closed', 'Rejected', 'Validating'].includes(x.status))
    .map((x) => ({
      id: clusterId(x.incident_id),
      incident_id: x.incident_id,
      title: x.title.replace(/^.*? — /, ''),
      cls: x.class as FailureClass,
      site_ids: x.site_ids,
      province_id: x.province_id,
      district_id: x.district_id,
      region: x.region,
      probability: x.probability,
      crossing_week: x.predicted_week,
      exposure_idr: x.exposure_idr,
      priority: x.priority_score,
      coverage: x.program_match,
      recommended_rank: x.recommended_rank,
      story: x.story,
      days_to_breach: x.days_to_breach,
    }))
    .sort((a, b) => b.priority - a.priority)
}

export function optionsFor(c: Cluster) {
  return db().optionsByIncident.get(c.incident_id) ?? []
}

// ---- Approval routing for a plan (DoA) -------------------------------------------------------
export interface PlanRoute {
  role: 'PLAN' | 'EXEC' | 'REGION' | 'OPS' | 'PROC'
  label: string
  cosign: string | null
  auto: boolean
  note: string
}

export function planRoute(cls: InterventionClass, totalIdr: number, p: Policy): PlanRoute {
  switch (cls) {
    case 'noncapex_zero':
      return { role: 'OPS', label: 'NOC shift lead', cosign: null, auto: true, note: 'Zero cost: auto-approved with post-hoc review' }
    case 'noncapex_opex':
      return totalIdr < p.opex_auto_approve_below_idr
        ? { role: 'REGION', label: 'Regional Network Manager', cosign: null, auto: true, note: `OpEx below ${Math.round(p.opex_auto_approve_below_idr / 1e6)}m: auto-approved` }
        : { role: 'REGION', label: 'Regional Network Manager', cosign: null, auto: false, note: 'Non-CapEx OpEx' }
    case 'capex_minor':
      return totalIdr <= p.decision_threshold_idr
        ? { role: 'REGION', label: 'Regional Network Manager', cosign: null, auto: false, note: `Minor CapEx at or below IDR ${Math.round(p.decision_threshold_idr / 1e6)}m` }
        : { role: 'PLAN', label: 'Head of Planning', cosign: null, auto: false, note: 'Minor CapEx above the Stage 3 threshold' }
    case 'capex_major':
      return { role: 'EXEC', label: 'Head of Network', cosign: totalIdr > p.cfo_cosign_above_idr ? 'CFO' : null, auto: false, note: 'Major CapEx' }
    default:
      return { role: 'PLAN', label: 'Head of Planning', cosign: null, auto: false, note: '' }
  }
}

// ---- Plans ------------------------------------------------------------------------------
export type PlanStatus = 'draft' | 'pending_approval' | 'approved' | 'handed_off' | 'rejected' | 'deferred'
export type HandoffState = 'not_sent' | 'sent' | 'acknowledged' | 'failed'

export interface P1Plan {
  id: string
  name: string
  status: PlanStatus
  cluster_id: string | null
  draft: PlanDraft
  created: string
  created_by: string
  submitted?: string
  decided?: string
  decided_by?: string
  reason?: string | null
  route: PlanRoute
  history: { ts: string; who: string; role: string; what: string; reason?: string | null }[]
  handoffs: Record<string, { state: HandoffState; ref?: string; ts?: string }>
}

export const HANDOFF_TARGETS = ['HO-ERP', 'HO-BOQ', 'HO-VENDOR', 'HO-TOWERCO', 'HO-WMS'] as const

export const PHASE1_ROLES = ['PLAN', 'PROC', 'EXEC', 'DEPLOY', 'OPS', 'REGION'] as const
