// The Predictive Planner agent layer (Phase 1). One agent, one job, one owner (PRD §7).
// Agents that touch money draft, never execute. Every output carries confidence, evidence and as-of date.

export type Stage = 'Sense' | 'Predict' | 'Decide' | 'Plan' | 'Govern'
export type Readiness = 'Exists' | 'Extend' | 'Build'

export interface IO {
  ref: string // source id (SRC-*), agent id (AG-*) or 'user'
  what: string
}

export interface AgentSpec {
  id: string
  name: string
  stage: Stage
  readiness: Readiness
  owner: string
  oneLiner: string
  business: string // what it does for the business, in plain language
  humanGate: string
  inputs: IO[]
  outputs: { name: string; fields: string }[]
  method: string
  runtime: string
  schedule: string
  sla: string
  api: string
  guardrails: string[]
  fallback: string
  kpis: string[]
  classes: string[] // 'all' or failure classes
  buildWeeks: number
  dependsOn: string[] // agent ids
}

export const AGENTS: AgentSpec[] = [
  {
    id: 'AG-FEAT',
    name: 'Feature Builder',
    stage: 'Sense',
    readiness: 'Build',
    owner: 'Netra data engineering · DevX',
    oneLiner: 'Turns raw counters, alarms, telemetry and external feeds into the daily feature set per site.',
    business: 'Makes sure every prediction is built on the same, fresh, explainable inputs. No feature, no prediction.',
    humanGate: 'None (automatic). Data-quality failures block downstream agents and alert the Netra on-call.',
    inputs: [
      { ref: 'SRC-OSS-PM', what: 'Hourly PRB, users, throughput, payload, availability' },
      { ref: 'SRC-FM', what: 'Normalised alarm events' },
      { ref: 'SRC-ITSM', what: 'Tickets and root causes' },
      { ref: 'SRC-SITE', what: 'Site, unit and battery inventory' },
      { ref: 'SRC-CM', what: 'Bands, carriers, software release' },
      { ref: 'SRC-RMS', what: 'Battery, rectifier, cabinet telemetry' },
      { ref: 'SRC-TNMS', what: 'Link utilisation, RSL, topology' },
      { ref: 'SRC-BMKG', what: 'Rain forecasts and outlook' },
      { ref: 'SRC-INARISK', what: 'Hazard and elevation attributes' },
    ],
    outputs: [{ name: 'feature_store.site_features_daily', fields: 'site_id, date, class, feature_id, value, window, source_as_of, quality_flag' }],
    method: '40 features (8 per class) over rolling windows (7 d to 12 mo). Point-in-time correct joins so back-tests never see the future. Missing values flagged, not imputed silently.',
    runtime: 'Netra batch (Spark), writes offline + online feature store',
    schedule: 'Daily 03:00 WIB after the 01:00–02:30 ingest',
    sla: 'Complete by 04:30 WIB; ≥ 98% of sites with full feature vectors',
    api: 'GET /nicc/v1/features/{site_id}?date=',
    guardrails: ['Point-in-time joins only', 'Feature drift (PSI) computed per run', 'Sites with > 2 missing critical features excluded and listed'],
    fallback: 'Re-use the previous day’s features with the age shown (D-2); predictions marked stale.',
    kpis: ['Feature completeness ≥ 98%', 'Run on time ≥ 99% of days', 'PSI < 0.2 per feature'],
    classes: ['all'],
    buildWeeks: 5,
    dependsOn: [],
  },
  {
    id: 'AG-SFP',
    name: 'Site Failure Prediction Agent',
    stage: 'Predict',
    readiness: 'Build',
    owner: 'IOH Network Operations · DevX delivery',
    oneLiner: 'Predicts the probability that each site fails or saturates in each of the next 8 weeks, by failure class.',
    business: 'The North Star: know which sites will fail 8 weeks before customers feel it, with a stated probability and the top reasons.',
    humanGate: 'None to run. A prediction only drives an approval once its class clears the 70% top-decile precision gate.',
    inputs: [{ ref: 'AG-FEAT', what: '8 features per class, rolling 90-day window' }],
    outputs: [
      { name: 'site_forecast', fields: 'site_id, run_date, class, p_w1..p_w8, ci90_low, ci90_high, crossing_week, model_version' },
      { name: 'site_explanations', fields: 'site_id, run_date, feature_id, value, contribution_pts' },
    ],
    method: 'Five gradient-boosted classifiers (LightGBM), one per class: capacity, power, transport, RAN hardware, environmental. Label = failure or breach inside the horizon. Isotonic calibration. SHAP contributions per site. No site turns red below 60%.',
    runtime: 'Netra model registry + batch scoring',
    schedule: 'Daily 05:00 WIB',
    sla: 'Scores for all sites by 05:30 WIB',
    api: 'GET /nicc/v1/forecast?class=&week=&min_p= · GET /nicc/v1/forecast/{site_id}/explain',
    guardrails: ['Calibrated probabilities with 90% interval', 'Red floor 60% (policy)', 'Class gate: ≥ 70% precision in the top decile on back-test before driving approvals', 'Champion/challenger on every retrain'],
    fallback: 'Hold the last good run and show its age; never extrapolate.',
    kpis: ['Precision at top decile ≥ 70% (per class)', 'Recall ≥ 50%', 'Calibration error < 5 pts', 'Override rate trend'],
    classes: ['capacity', 'power', 'transport', 'ran_hardware', 'environmental'],
    buildWeeks: 8,
    dependsOn: ['AG-FEAT'],
  },
  {
    id: 'AG-CAP',
    name: 'Capacity Exhaustion Agent',
    stage: 'Predict',
    readiness: 'Extend',
    owner: 'Network Planning',
    oneLiner: 'Projects weeks to saturation per cell from PRB trend, traffic growth and events.',
    business: 'Gives planners a date, not a score: “Bekasi saturates in 23 days”.',
    humanGate: 'None (feeds the forecast and the plan window).',
    inputs: [
      { ref: 'AG-FEAT', what: 'PRB P95, slope, traffic growth, device mix' },
      { ref: 'SRC-EVENTS', what: 'Planned events by district' },
    ],
    outputs: [{ name: 'cell_saturation', fields: 'cell_id, weeks_to_saturation, saturation_date, driver' }],
    method: 'Robust trend (Theil–Sen) on busy-hour PRB with seasonal adjustment and event uplift; reconciled with the capacity-class probability.',
    runtime: 'Netra batch',
    schedule: 'Daily 05:00 WIB',
    sla: 'By 05:30 WIB',
    api: 'GET /nicc/v1/capacity/{site_id}',
    guardrails: ['Saturation threshold editable (default 90% busy-hour PRB)', 'Event uplift capped and shown separately'],
    fallback: 'Linear projection with wider band.',
    kpis: ['Saturation date error ≤ 1 week at W+4'],
    classes: ['capacity'],
    buildWeeks: 3,
    dependsOn: ['AG-FEAT'],
  },
  {
    id: 'AG-ENERGY',
    name: 'Energy and Power Agent',
    stage: 'Sense',
    readiness: 'Build',
    owner: 'Network Operations · Power',
    oneLiner: 'Tracks battery health, generator dependence and grid outages per site.',
    business: 'Feeds the power-failure model and surfaces the largest non-CapEx saving pool: energy OpEx.',
    humanGate: 'None (signals only).',
    inputs: [
      { ref: 'SRC-RMS', what: 'Battery SoH, DoD, rectifier load, temperature' },
      { ref: 'SRC-FUEL', what: 'Run hours and fuel' },
      { ref: 'SRC-PLN', what: 'Mains failures' },
    ],
    outputs: [{ name: 'site_energy_profile', fields: 'site_id, battery_eol_date, genset_dependence, energy_opex_idr' }],
    method: 'Battery end-of-life from discharge-curve degradation; genset dependence index; anomaly detection on fuel per run hour.',
    runtime: 'Netra batch',
    schedule: 'Daily 04:00 WIB',
    sla: 'By 04:30 WIB',
    api: 'GET /nicc/v1/energy/{site_id}',
    guardrails: ['Sites without RMS use alarm proxies and are flagged “proxy”'],
    fallback: 'Alarm-derived proxies only.',
    kpis: ['Battery EOL prediction within ± 30 days'],
    classes: ['power'],
    buildWeeks: 4,
    dependsOn: [],
  },
  {
    id: 'AG-TRANS',
    name: 'Backbone and Transport Agent',
    stage: 'Sense',
    readiness: 'Build',
    owner: 'Transport Engineering',
    oneLiner: 'Finds transport bottlenecks and single points of failure, with the sites that depend on them.',
    business: 'One congested microwave hop can take down nine sites; this agent finds it before it does.',
    humanGate: 'None (signals only).',
    inputs: [{ ref: 'SRC-TNMS', what: 'Utilisation, RSL, protection, topology' }],
    outputs: [{ name: 'link_risk', fields: 'link_id, util_p95, fade_events, protected, dependent_site_ids[]' }],
    method: 'Topology graph traversal for dependent sites; utilisation trend and fade-event detection per hop.',
    runtime: 'Netra batch',
    schedule: 'Daily 04:00 WIB',
    sla: 'By 04:30 WIB',
    api: 'GET /nicc/v1/transport/links/{link_id}',
    guardrails: ['Topology confidence shown; manually maintained links flagged'],
    fallback: 'Utilisation-only risk without dependents.',
    kpis: ['Dependent-site accuracy ≥ 95% vs field audit'],
    classes: ['transport'],
    buildWeeks: 4,
    dependsOn: [],
  },
  {
    id: 'AG-REV',
    name: 'Revenue Exposure Agent',
    stage: 'Predict',
    readiness: 'Build',
    owner: 'Finance BI',
    oneLiner: 'Puts an IDR value on every predicted failure: revenue at risk per month.',
    business: 'Lets the Head of Planning rank by money at risk, not by alarm count.',
    humanGate: 'None. Method agreed with Finance before go-live.',
    inputs: [
      { ref: 'SRC-REV', what: 'Catchment revenue' },
      { ref: 'SRC-CNX', what: 'Segment mix and CNX' },
      { ref: 'AG-SFP', what: 'Class and probability' },
    ],
    outputs: [{ name: 'exposure', fields: 'site_id | cluster_id, exposure_idr_month, method_version' }],
    method: 'Catchment revenue × class-specific at-risk share (capacity 28%, power 33%, transport 42%, RAN 30%, environmental 36%, placeholders) + enterprise SLA penalties.',
    runtime: 'Netra batch',
    schedule: 'Daily 05:30 WIB',
    sla: 'By 06:00 WIB',
    api: 'GET /nicc/v1/exposure/{site_id}',
    guardrails: ['At-risk shares are policy, editable, versioned'],
    fallback: 'Last month’s revenue with age shown.',
    kpis: ['Finance sign-off of method'],
    classes: ['all'],
    buildWeeks: 2,
    dependsOn: ['AG-SFP'],
  },
  {
    id: 'AG-CLUSTER',
    name: 'Forecast Orchestrator',
    stage: 'Predict',
    readiness: 'Build',
    owner: 'NICC platform',
    oneLiner: 'Groups site predictions into clusters by root cause (one cluster per cause, not per site).',
    business: '14 Bekasi sites become one decision, not 14 tickets.',
    humanGate: 'None (automatic grouping; planners can split or merge).',
    inputs: [
      { ref: 'AG-SFP', what: 'Predictions' },
      { ref: 'AG-TRANS', what: 'Shared links' },
      { ref: 'SRC-SITE', what: 'Geography, cluster' },
    ],
    outputs: [{ name: 'forecast_cluster', fields: 'cluster_id, class, site_ids[], crossing_week, exposure_idr, priority_score' }],
    method: 'Spatial-temporal clustering (DBSCAN on site distance within district, same class, crossing week ± 1); transport clusters grouped by shared link.',
    runtime: 'NICC service',
    schedule: 'After each forecast run',
    sla: '≤ 10 min',
    api: 'GET /nicc/v1/clusters',
    guardrails: ['Never merge across classes', 'Planner split/merge is logged'],
    fallback: 'Site-level list.',
    kpis: ['Clusters per 100 predictions', 'Planner merge/split rate'],
    classes: ['all'],
    buildWeeks: 2,
    dependsOn: ['AG-SFP', 'AG-REV'],
  },
  {
    id: 'AG-SMARTCAPEX',
    name: 'Smart CapEx Agent',
    stage: 'Decide',
    readiness: 'Exists',
    owner: 'Network Planning',
    oneLiner: 'Classifies each predicted site CapEx or non-CapEx and ranks it (existing engine, consumed as-is).',
    business: 'Brings 18 months of proven investment logic into the forecast instead of a parallel spreadsheet.',
    humanGate: 'Planner may move a site between classes with a reason (logged, fed back).',
    inputs: [{ ref: 'SRC-SMARTCAPEX', what: 'Ranking and CapEx flag (D-5)' }],
    outputs: [{ name: 'capex_classification', fields: 'site_id, class: capex|noncapex, rank, rationale_codes, as_of (D-5)' }],
    method: 'Existing Smart CapEx model; NICC reads its output and shows the age. No retraining in Phase 1.',
    runtime: 'Existing Netra job',
    schedule: 'Daily on D-5 data',
    sla: 'Existing',
    api: 'GET /nicc/v1/smartcapex/{site_id}',
    guardrails: ['Read-only consumption', 'Overrides exported to the Smart CapEx owner'],
    fallback: 'Action Ladder classification only.',
    kpis: ['Override rate', 'Agreement with Action Ladder'],
    classes: ['all'],
    buildWeeks: 1,
    dependsOn: [],
  },
  {
    id: 'AG-LADDER',
    name: 'Action Ladder Agent',
    stage: 'Decide',
    readiness: 'Build',
    owner: 'NICC platform · Network Planning',
    oneLiner: 'Lists intervention options per cluster, cheapest first, with cost, lead time, uplift and whether it fits the window.',
    business: 'Makes refarming and parameter fixes the first rung, so CapEx is spent only where it is needed.',
    humanGate: 'Recommendation only; the approver picks the rung.',
    inputs: [
      { ref: 'AG-CLUSTER', what: 'Cluster, class, window' },
      { ref: 'AG-SPECTRUM', what: 'Refarming options' },
      { ref: 'SRC-ERP', what: 'Price book' },
      { ref: 'SRC-SITE', what: 'Site class, structure' },
    ],
    outputs: [{ name: 'action_options', fields: 'cluster_id, rank, intervention, class, cost_idr, lead_days, predicted_uplift, confidence, fits_window, bridge' }],
    method: 'Class-specific intervention templates (5 classes × 3–5 rungs) costed from the price book; uplift from historical post-RFS results; bridge proposed when the best rung is longer than the window.',
    runtime: 'NICC service',
    schedule: 'On cluster creation and on change',
    sla: '≤ 1 min per cluster',
    api: 'GET /nicc/v1/clusters/{id}/options',
    guardrails: ['Always includes a zero-cost rung where one exists', 'Uplift claims cite their evidence'],
    fallback: 'Static templates without uplift.',
    kpis: ['Share of approvals choosing a non-CapEx rung', 'Predicted vs realised uplift'],
    classes: ['all'],
    buildWeeks: 3,
    dependsOn: ['AG-CLUSTER'],
  },
  {
    id: 'AG-SPECTRUM',
    name: 'Spectrum and Refarming Agent',
    stage: 'Decide',
    readiness: 'Build',
    owner: 'Network Planning · Spectrum',
    oneLiner: 'Finds zero-CapEx refarming and carrier moves that relieve a loaded band.',
    business: 'Buys 2–4 weeks for free while hardware is built, the bridge in every capacity plan.',
    humanGate: 'Zero-cost changes auto-approve with post-hoc review (policy).',
    inputs: [
      { ref: 'SRC-CM', what: 'Bands and carriers' },
      { ref: 'SRC-SPECTRUM', what: 'Holdings' },
      { ref: 'SRC-OSS-PM', what: 'Band utilisation, 2G/4G/5G split' },
    ],
    outputs: [{ name: 'refarm_options', fields: 'site_id, from_band, to_band, mhz, prb_relief_pts, weeks_bought' }],
    method: 'Rule-based band utilisation analysis with device-mix constraints.',
    runtime: 'NICC service',
    schedule: 'On capacity cluster creation',
    sla: '≤ 1 min',
    api: 'GET /nicc/v1/spectrum/{site_id}/options',
    guardrails: ['No 2G sunset where voice-only device share > threshold'],
    fallback: 'No refarming rung offered.',
    kpis: ['Weeks bought vs predicted'],
    classes: ['capacity'],
    buildWeeks: 2,
    dependsOn: [],
  },
  {
    id: 'AG-MATCH',
    name: 'Program Match Agent',
    stage: 'Decide',
    readiness: 'Build',
    owner: 'NICC platform',
    oneLiner: 'Checks whether a predicted cluster is already covered by a plan or program, and whether it lands in time.',
    business: 'Stops double-spending and shows the real gap: “27 covered, 14 not”.',
    humanGate: 'None (verdict only).',
    inputs: [
      { ref: 'AG-CLUSTER', what: 'Cluster sites and crossing week' },
      { ref: 'SRC-ERP', what: 'Open programs / POs' },
    ],
    outputs: [{ name: 'coverage_verdict', fields: 'cluster_id, verdict: covered|partial|not_covered, program_id, eta, reason' }],
    method: 'Site-set overlap plus ETA vs predicted crossing date.',
    runtime: 'NICC service',
    schedule: 'On cluster creation and program change',
    sla: '≤ 1 min',
    api: 'GET /nicc/v1/clusters/{id}/coverage',
    guardrails: ['“Partial” always states why'],
    fallback: 'Not covered (conservative).',
    kpis: ['Verdict accuracy vs PMO review'],
    classes: ['all'],
    buildWeeks: 1,
    dependsOn: ['AG-CLUSTER'],
  },
  {
    id: 'AG-PRIORITY',
    name: 'Priority Scoring Agent',
    stage: 'Decide',
    readiness: 'Build',
    owner: 'NICC platform',
    oneLiner: 'Ranks clusters by exposure × probability × urgency.',
    business: 'The forecast board opens on the decisions worth the most money this week.',
    humanGate: 'Weights editable in policy.',
    inputs: [
      { ref: 'AG-REV', what: 'Exposure' },
      { ref: 'AG-SFP', what: 'Probability and crossing week' },
    ],
    outputs: [{ name: 'priority', fields: 'cluster_id, score, components' }],
    method: 'score = exposure^a × p^b × urgency^c, urgency decaying with weeks to breach.',
    runtime: 'NICC service',
    schedule: 'On change',
    sla: 'Real time',
    api: 'GET /nicc/v1/clusters?sort=priority',
    guardrails: ['Weights versioned in the audit log'],
    fallback: 'Sort by exposure.',
    kpis: ['Top-10 stability week on week'],
    classes: ['all'],
    buildWeeks: 1,
    dependsOn: ['AG-REV', 'AG-SFP'],
  },
  {
    id: 'AG-BOQ',
    name: 'BOQ Agent',
    stage: 'Plan',
    readiness: 'Build',
    owner: 'Deployment PMO',
    oneLiner: 'Drafts the bill of quantities for the chosen intervention, per site, from the price book.',
    business: 'BOQ in minutes instead of 2–3 weeks; variance vs the price book flagged automatically.',
    humanGate: 'Deployment lead approves if variance > 10% vs price book.',
    inputs: [
      { ref: 'AG-LADDER', what: 'Chosen intervention' },
      { ref: 'SRC-SITE', what: 'Site class, structure' },
      { ref: 'SRC-ERP', what: 'Price book, SKU mapping' },
    ],
    outputs: [{ name: 'boq_draft', fields: 'plan_id, site_id, sku, erp_material_code, qty, unit_price_idr, variance_pct' }],
    method: 'Intervention templates × site attributes (e.g. sector add adds antenna, two RRUs, board, mount, cabling, services, tower company fee).',
    runtime: 'NICC service',
    schedule: 'On plan build',
    sla: '≤ 30 s per plan',
    api: 'POST /nicc/v1/plans/{id}/boq:draft',
    guardrails: ['Draft only: never posts to ERP', 'Variance > 10% routes to Deployment lead'],
    fallback: 'Template BOQ without site adjustments.',
    kpis: ['BOQ variance vs final PO', 'Planner edits per BOQ'],
    classes: ['all'],
    buildWeeks: 3,
    dependsOn: ['AG-LADDER'],
  },
  {
    id: 'AG-WAREHOUSE',
    name: 'Warehouse Readiness Agent',
    stage: 'Plan',
    readiness: 'Build',
    owner: 'Supply Chain',
    oneLiner: 'Checks every BOQ line against stock in 8 warehouses and proposes transfers and pre-positioning.',
    business: 'Pre-positions parts six weeks before the failure: “Semarang has 9 of 14 antennas”.',
    humanGate: 'Procurement approves pre-positioning and reservations.',
    inputs: [
      { ref: 'AG-BOQ', what: 'BOQ lines' },
      { ref: 'SRC-WMS', what: 'On hand, reserved, reorder points' },
    ],
    outputs: [{ name: 'stock_readiness', fields: 'plan_id, sku, needed, sources[{warehouse, qty, transfer_days}], shortfall, readiness: green|amber|red' }],
    method: 'Nearest-warehouse allocation within region, then cross-region transfers, then PO for shortfall; readiness by lead time vs window.',
    runtime: 'NICC service',
    schedule: 'On plan build; daily re-check',
    sla: '≤ 30 s',
    api: 'POST /nicc/v1/plans/{id}/stock:check',
    guardrails: ['Reservations are soft until Procurement approves'],
    fallback: 'Readiness unknown (grey).',
    kpis: ['Share of BOQ lines green at approval', 'Stock-outs at installation'],
    classes: ['all'],
    buildWeeks: 2,
    dependsOn: ['AG-BOQ'],
  },
  {
    id: 'AG-PROC',
    name: 'Procurement Agent',
    stage: 'Plan',
    readiness: 'Build',
    owner: 'Procurement',
    oneLiner: 'Drafts the purchase order for the shortfall and services against the right framework agreement.',
    business: 'BOQ-to-PO in 3 days instead of 3–4 weeks, without anyone re-keying.',
    humanGate: 'Procurement releases the PO in ERP (Phase 1 hand-off).',
    inputs: [
      { ref: 'AG-WAREHOUSE', what: 'Shortfall' },
      { ref: 'AG-BOQ', what: 'Services lines' },
      { ref: 'SRC-ERP', what: 'Contracts, ceilings, vendor ids' },
    ],
    outputs: [{ name: 'po_draft', fields: 'plan_id, vendor_id, contract_id, lines[{erp_material_code, qty, price}], total_idr, ceiling_check' }],
    method: 'Contract selection by vendor, region and category; ceiling and validity checks.',
    runtime: 'NICC service',
    schedule: 'On plan approval',
    sla: '≤ 1 min',
    api: 'POST /nicc/v1/plans/{id}/po:draft → ERP PO draft (BAPI / file drop)',
    guardrails: ['Draft only: Procurement releases in ERP', 'Contract ceiling breach blocks the draft'],
    fallback: 'Export CSV for manual entry.',
    kpis: ['Draft-to-release time', 'Drafts rejected by ERP'],
    classes: ['all'],
    buildWeeks: 3,
    dependsOn: ['AG-WAREHOUSE', 'AG-BOQ'],
  },
  {
    id: 'AG-VENDOR',
    name: 'Vendor Allocation Agent',
    stage: 'Plan',
    readiness: 'Build',
    owner: 'Deployment PMO',
    oneLiner: 'Proposes the rollout vendor per plan from region coverage, free capacity and SLA history.',
    business: 'Allocates work where there is capacity, before the plan is approved, not after.',
    humanGate: 'Deployment lead confirms the allocation.',
    inputs: [{ ref: 'SRC-VPORTAL', what: 'Capacity, SLA, active allocations' }],
    outputs: [{ name: 'vendor_proposal', fields: 'plan_id, vendor_id, free_capacity, sla_pct, alternatives[]' }],
    method: 'Score = free capacity × SLA within region; cross-region with mobilisation penalty.',
    runtime: 'NICC service',
    schedule: 'On plan build',
    sla: '≤ 30 s',
    api: 'POST /nicc/v1/plans/{id}/vendor:propose',
    guardrails: ['Proposal only; never commits vendor capacity'],
    fallback: 'Planner selects manually.',
    kpis: ['Proposals accepted', 'SLA of allocated work'],
    classes: ['all'],
    buildWeeks: 2,
    dependsOn: [],
  },
  {
    id: 'AG-TOWERCO',
    name: 'Tower Company Coordination Agent',
    stage: 'Plan',
    readiness: 'Build',
    owner: 'Deployment · Tower relations',
    oneLiner: 'Drafts loading-feasibility and access requests to tower companies at approval time.',
    business: 'Removes the 2–4 week tower company wait from the critical path by starting it on day one.',
    humanGate: 'Tower relations sends the request.',
    inputs: [
      { ref: 'SRC-TOWERCO', what: 'Lease, loading allowance' },
      { ref: 'AG-BOQ', what: 'Equipment added (weight, wind load)' },
    ],
    outputs: [{ name: 'access_request_draft', fields: 'plan_id, tower_company, site_ids[], loading_delta_kg, requested_date, sla_days' }],
    method: 'Template per tower company; loading delta from BOQ equipment specs.',
    runtime: 'NICC service',
    schedule: 'On plan approval',
    sla: '≤ 1 min',
    api: 'POST /nicc/v1/plans/{id}/towerco:draft',
    guardrails: ['Draft only', 'Loading over allowance flagged as structural review'],
    fallback: 'Manual request.',
    kpis: ['Tower company response time vs SLA'],
    classes: ['capacity', 'transport'],
    buildWeeks: 2,
    dependsOn: ['AG-BOQ'],
  },
  {
    id: 'AG-ROUTE',
    name: 'Approval Routing Agent',
    stage: 'Govern',
    readiness: 'Build',
    owner: 'NICC platform · Network PMO',
    oneLiner: 'Names the approver for each plan from intervention class, IDR value and scope.',
    business: 'Every plan reaches the right person on day one, per IOH’s delegation of authority.',
    humanGate: 'Is the gate: named approver approves, rejects (with reason) or defers.',
    inputs: [
      { ref: 'AG-LADDER', what: 'Intervention class, cost' },
      { ref: 'user', what: 'Delegation-of-authority matrix (policy)' },
    ],
    outputs: [{ name: 'approval_route', fields: 'plan_id, approver_role, approver_name, cosign, auto_rule' }],
    method: 'Rules engine over the DoA matrix (editable, versioned).',
    runtime: 'NICC service',
    schedule: 'On submit',
    sla: 'Real time',
    api: 'POST /nicc/v1/plans/{id}:submit',
    guardrails: ['No agent both recommends and approves', 'CFO co-sign above IDR 2bn'],
    fallback: 'Route to Head of Planning.',
    kpis: ['Decision time per gate', 'Plans approved inside SLA'],
    classes: ['all'],
    buildWeeks: 1,
    dependsOn: ['AG-LADDER'],
  },
  {
    id: 'AG-NARRATIVE',
    name: 'Narrative Agent',
    stage: 'Govern',
    readiness: 'Build',
    owner: 'NICC platform',
    oneLiner: 'Writes the plain-language summary of each cluster and plan for the approver.',
    business: 'The Head of Planning reads three sentences, not a spreadsheet.',
    humanGate: 'None (text only; numbers always come from the agents, never from the model).',
    inputs: [{ ref: 'AG-CLUSTER', what: 'Cluster, options, coverage' }],
    outputs: [{ name: 'summary', fields: 'object_id, role, text, sources[]' }],
    method: 'LLM with templated prompts; every number injected from structured agent output and cited.',
    runtime: 'NICC service (LLM)',
    schedule: 'On change',
    sla: '≤ 5 s',
    api: 'GET /nicc/v1/narrative/{object_id}?role=',
    guardrails: ['No free-form numbers', 'Bahasa Indonesia variant later'],
    fallback: 'Template text.',
    kpis: ['Approver edits'],
    classes: ['all'],
    buildWeeks: 1,
    dependsOn: ['AG-CLUSTER'],
  },
  {
    id: 'AG-DRIFT',
    name: 'Model Drift Agent',
    stage: 'Govern',
    readiness: 'Build',
    owner: 'Netra Model Ops',
    oneLiner: 'Compares predictions with realised failures and watches feature drift.',
    business: 'Keeps the precision number honest after go-live, not only in the back-test.',
    humanGate: 'Model owner decides retrain or rollback.',
    inputs: [
      { ref: 'AG-SFP', what: 'Predictions' },
      { ref: 'SRC-ITSM', what: 'Realised outcomes' },
      { ref: 'AG-FEAT', what: 'Feature distributions' },
    ],
    outputs: [{ name: 'model_scorecard', fields: 'class, month, precision_top_decile, recall, calibration_error, psi' }],
    method: 'Monthly realised precision/recall, calibration; PSI per feature; alerts on breach.',
    runtime: 'Netra batch',
    schedule: 'Weekly (Mon), monthly report',
    sla: '—',
    api: 'GET /nicc/v1/models/{class}/scorecard',
    guardrails: ['A class drops to advisory if realised precision < 70% for two months'],
    fallback: '—',
    kpis: ['Time to detect drift'],
    classes: ['all'],
    buildWeeks: 2,
    dependsOn: ['AG-SFP'],
  },
  {
    id: 'AG-LEARN',
    name: 'Override Learning Agent',
    stage: 'Govern',
    readiness: 'Build',
    owner: 'Netra Model Ops',
    oneLiner: 'Turns every rejection, class move and false-positive mark into labelled training data.',
    business: 'Each planner override makes next month’s model better.',
    humanGate: 'None (collects labels).',
    inputs: [{ ref: 'user', what: 'Rejections, overrides, reason codes' }],
    outputs: [{ name: 'labels', fields: 'object_id, agent, recommended, chosen, reason_code, ts' }],
    method: 'Reason-code taxonomy; labels exported to Netra for retraining and to Smart CapEx owners.',
    runtime: 'NICC service → Netra',
    schedule: 'Daily 23:00 WIB',
    sla: '—',
    api: 'GET /nicc/v1/overrides?since=',
    guardrails: ['Reason code mandatory'],
    fallback: '—',
    kpis: ['Labels per week', 'Override rate trend'],
    classes: ['all'],
    buildWeeks: 1,
    dependsOn: [],
  },
]

export const STAGES: { id: Stage; label: string; desc: string }[] = [
  { id: 'Sense', label: 'Sense', desc: 'Build features and domain signals from Netra data' },
  { id: 'Predict', label: 'Predict', desc: 'Probability, date and IDR value of each failure' },
  { id: 'Decide', label: 'Decide', desc: 'Coverage, priority, CapEx class and options' },
  { id: 'Plan', label: 'Plan (draft only)', desc: 'BOQ, stock, PO draft, vendor, tower company' },
  { id: 'Govern', label: 'Govern', desc: 'Approval, narrative, drift and learning' },
]

// Architecture layers (top = people, bottom = systems of record)
export const LAYERS = [
  { id: 'L6', name: 'Experience', items: ['Predictive Planner UI (/phase1)', 'Role lenses: PLAN, PROC, EXEC, DEPLOY, OPS, REGION', 'IOH SSO, scope enforced at query level'] },
  { id: 'L5', name: 'Orchestration and workflow', items: ['Planner workflow: predict → classify → plan → approve → hand off', 'Approval Routing (DoA)', 'Audit log (5-year retention)', 'Notifications'] },
  { id: 'L4', name: 'Agent runtime', items: ['Predict: SFP, Capacity, Revenue, Forecast Orchestrator', 'Decide: Smart CapEx, Ladder, Spectrum, Match, Priority', 'Plan: BOQ, Warehouse, Procurement, Vendor, Tower co', 'Govern: Narrative, Drift, Learning'] },
  { id: 'L3', name: 'Model and feature layer (Netra)', items: ['Feature store (offline + online)', 'Model registry: 5 class models, champion/challenger', 'Batch scoring 05:00 WIB'] },
  { id: 'L2', name: 'Data layer (Netra lake)', items: ['Bronze: raw extracts', 'Silver: harmonised KPIs, normalised alarms, site master', 'Gold: site × day features and labels'] },
  { id: 'L1', name: 'Sources and systems of record', items: ['OSS PM / FM / CM (4 RAN vendors)', 'ITSM, site master, Smart CapEx, CNX, revenue', 'RMS, fuel, TNMS, BMKG, InaRISK', 'ERP, WMS, vendor portal, tower company lease DB'] },
]

// Daily batch (WIB)
export const SCHEDULE = [
  { time: '01:00', what: 'Ingest OSS PM, FM, CM, tickets, WMS, ERP extracts', owner: 'Netra' },
  { time: '03:00', what: 'Feature Builder: 40 features × 60k sites', owner: 'AG-FEAT' },
  { time: '04:00', what: 'Energy and Transport signals', owner: 'AG-ENERGY · AG-TRANS' },
  { time: '05:00', what: 'Scoring: 5 class models, capacity saturation dates', owner: 'AG-SFP · AG-CAP' },
  { time: '05:30', what: 'Revenue exposure, clustering, coverage, priority', owner: 'AG-REV · AG-CLUSTER · AG-MATCH · AG-PRIORITY' },
  { time: '06:00', what: 'Smart CapEx classification read (D-5), action ladders, narratives', owner: 'AG-SMARTCAPEX · AG-LADDER · AG-NARRATIVE' },
  { time: '06:30', what: 'Stock re-check on open plans', owner: 'AG-WAREHOUSE' },
  { time: '08:00', what: 'Planners and approvers start the day on fresh data', owner: 'People' },
  { time: '23:00', what: 'Overrides and outcomes exported to Netra', owner: 'AG-LEARN' },
]
