// Phase 1 data sources: what the Predictive Planner needs, where it lives today, and how it reaches Netra.
// Statuses are DevX's working assumption for the validation session; IOH's Netra team confirms each row.

export type NetraStatus = 'on_netra' | 'partial' | 'not_on_netra'
export type Criticality = 'blocking' | 'important' | 'enhancing'

export interface SourceField {
  name: string
  type: string
  description: string
}

export interface DataSource {
  id: string
  name: string
  domain: 'Network performance' | 'Faults and tickets' | 'Inventory and config' | 'Customer and revenue' | 'Power and energy' | 'Transport' | 'External' | 'Supply chain' | 'Planning outputs'
  systems: string
  owner: string
  grain: string
  refresh: string
  latency: string
  historyNeeded: string
  historyAvailable: string
  volume: string
  status: NetraStatus
  integration: string
  pii: boolean
  quality: number // 0-100 working estimate
  qualityNotes: string
  criticality: Criticality
  classes: string[] // failure classes that depend on it ('all' for every class)
  gap?: string // what must happen before go-live
  fields: SourceField[]
}

export const SOURCES: DataSource[] = [
  {
    id: 'SRC-OSS-PM',
    name: 'RAN performance counters',
    domain: 'Network performance',
    systems: 'Ericsson ENM, Nokia NetAct, Huawei U2020 / iMaster MAE, ZTE UME',
    owner: 'Network Operations · OSS',
    grain: 'Cell × 15 min, aggregated to cell × hour and site × day',
    refresh: 'Daily batch 01:00 WIB',
    latency: 'D-1',
    historyNeeded: '24 months (back-test) + rolling 90 days (features)',
    historyAvailable: '13 months on Netra; older in vendor OSS archives',
    volume: '~1.4 bn rows / month at hourly grain (60k sites)',
    status: 'on_netra',
    integration: 'Netra batch connector (existing)',
    pii: false,
    quality: 88,
    qualityNotes: 'Counter names differ by vendor; harmonised KPI layer exists for PRB and throughput, not yet for RRC users on ZTE.',
    criticality: 'blocking',
    classes: ['capacity', 'ran_hardware'],
    gap: 'Backfill 11 months from OSS archives for the 24-month back-test; harmonise ZTE RRC counter.',
    fields: [
      { name: 'cell_id', type: 'string', description: 'Global cell identifier, joins to site master' },
      { name: 'ts_hour', type: 'timestamp WIB', description: 'Hour bucket' },
      { name: 'prb_dl_util_pct', type: 'float', description: 'DL PRB utilisation' },
      { name: 'prb_ul_util_pct', type: 'float', description: 'UL PRB utilisation' },
      { name: 'rrc_conn_users_avg', type: 'float', description: 'Mean RRC-connected users' },
      { name: 'dl_user_tput_mbps', type: 'float', description: 'Mean DL user throughput' },
      { name: 'payload_dl_gb', type: 'float', description: 'DL data volume' },
      { name: 'cell_avail_pct', type: 'float', description: 'Cell availability' },
      { name: 'board_temp_max_c', type: 'float', description: 'Max baseband board temperature (where exposed)' },
    ],
  },
  {
    id: 'SRC-FM',
    name: 'Fault management alarms',
    domain: 'Faults and tickets',
    systems: 'Vendor OSS FM, umbrella NMS',
    owner: 'Network Operations · NOC',
    grain: 'Alarm event (raise / clear)',
    refresh: 'Hourly batch (stream in Phase 2)',
    latency: '≤ 1 h',
    historyNeeded: '24 months',
    historyAvailable: '18 months on Netra',
    volume: '~25 m events / month',
    status: 'on_netra',
    integration: 'Netra batch connector (existing)',
    pii: false,
    quality: 81,
    qualityNotes: 'Alarm taxonomy not normalised across vendors; ~6% events without site mapping.',
    criticality: 'blocking',
    classes: ['power', 'ran_hardware', 'transport'],
    gap: 'Map vendor alarm codes to NICC classes (rectifier, mains failure, VSWR, board fault).',
    fields: [
      { name: 'alarm_id', type: 'string', description: 'Unique event id' },
      { name: 'site_id', type: 'string', description: 'Site identifier' },
      { name: 'alarm_code', type: 'string', description: 'Vendor alarm code' },
      { name: 'nicc_alarm_class', type: 'enum', description: 'Normalised: mains_failure, rectifier, battery_low, vswr, board, link, temp' },
      { name: 'severity', type: 'enum', description: 'critical / major / minor' },
      { name: 'raised_at / cleared_at', type: 'timestamp', description: 'Event window' },
    ],
  },
  {
    id: 'SRC-SITE',
    name: 'Site master and inventory',
    domain: 'Inventory and config',
    systems: 'Network Planning site database, asset register',
    owner: 'Network Planning',
    grain: 'Site, cell, installed unit',
    refresh: 'Daily snapshot',
    latency: 'D-1',
    historyNeeded: 'Current + change log',
    historyAvailable: 'Current snapshot only',
    volume: '~60k sites, ~180k cells, ~400k units',
    status: 'partial',
    integration: 'Netra batch connector (existing, extend for unit-level inventory)',
    pii: false,
    quality: 74,
    qualityNotes: 'Coordinates good; unit install dates missing for ~22% of RRUs; battery install dates rarely recorded; elevation absent.',
    criticality: 'blocking',
    classes: ['all'],
    gap: 'Data quality sprint: unit install dates, battery bank records, plinth height; derive elevation from DEM. Unknowns shown grey, never guessed.',
    fields: [
      { name: 'site_id', type: 'string', description: 'Province code + number, e.g. JBR-1104' },
      { name: 'lat / lon', type: 'float', description: 'WGS84 coordinates' },
      { name: 'district_code', type: 'string', description: 'BPS kabupaten/kota code' },
      { name: 'site_class', type: 'enum', description: 'macro, small cell, IBS, DAS' },
      { name: 'tower_company', type: 'string', description: 'Mitratel, Protelindo, TBIG, EdgePoint, own' },
      { name: 'power_type / backhaul_type', type: 'enum', description: 'grid, grid+genset, genset, solar hybrid / fibre, MW, satellite' },
      { name: 'unit_serial, unit_type, install_date', type: 'string, enum, date', description: 'RRU / BBU / battery inventory' },
    ],
  },
  {
    id: 'SRC-CM',
    name: 'Configuration management',
    domain: 'Inventory and config',
    systems: 'Vendor OSS CM exports',
    owner: 'Network Operations · RAN',
    grain: 'Cell parameter snapshot',
    refresh: 'Daily',
    latency: 'D-1',
    historyNeeded: '90 days',
    historyAvailable: 'Not on Netra',
    volume: '~180k cells × 40 params',
    status: 'partial',
    integration: 'Netra batch connector (new extract)',
    pii: false,
    quality: 70,
    qualityNotes: 'Carrier bandwidth and band available; software release version only for Ericsson and Nokia today.',
    criticality: 'important',
    classes: ['capacity', 'ran_hardware'],
    gap: 'Add daily CM extract (band, bandwidth, carriers, SW release) for all four vendors.',
    fields: [
      { name: 'cell_id', type: 'string', description: 'Cell' },
      { name: 'band / bandwidth_mhz', type: 'enum / int', description: 'L900, L1800, L2100, L2300, NR' },
      { name: 'carrier_count', type: 'int', description: 'Active carriers' },
      { name: 'sw_release', type: 'string', description: 'Software release (for firmware lag)' },
    ],
  },
  {
    id: 'SRC-ITSM',
    name: 'Trouble tickets and work orders',
    domain: 'Faults and tickets',
    systems: 'ITSM / ticketing (to confirm with IOH)',
    owner: 'Network Operations · Field',
    grain: 'Ticket',
    refresh: 'Daily',
    latency: 'D-1',
    historyNeeded: '24 months (labels and history features)',
    historyAvailable: '24 months',
    volume: '~90k tickets / month',
    status: 'on_netra',
    integration: 'Netra batch connector (existing)',
    pii: false,
    quality: 68,
    qualityNotes: 'Root-cause field free text for ~40% of tickets; NLP classification needed to build failure labels.',
    criticality: 'blocking',
    classes: ['all'],
    gap: 'Root-cause classifier on ticket text to produce training labels per class (back-test precision depends on it).',
    fields: [
      { name: 'ticket_id', type: 'string', description: 'Ticket' },
      { name: 'site_id', type: 'string', description: 'Site' },
      { name: 'opened_at / resolved_at', type: 'timestamp', description: 'Outage window' },
      { name: 'root_cause', type: 'text → enum', description: 'Battery, rectifier, genset, fibre cut, MW, hardware, flood, capacity' },
      { name: 'parts_replaced', type: 'string[]', description: 'Hardware swaps' },
    ],
  },
  {
    id: 'SRC-CNX',
    name: 'CNX scores',
    domain: 'Customer and revenue',
    systems: 'CNX Agent on Netra (77 iterations, extending to 5G)',
    owner: 'CX Analytics',
    grain: 'Site × segment × day',
    refresh: 'Daily',
    latency: 'D-1',
    historyNeeded: '12 months',
    historyAvailable: '12 months',
    volume: '~240k rows / day',
    status: 'on_netra',
    integration: 'Netra table (existing)',
    pii: true,
    quality: 90,
    qualityNotes: 'Customer-level scores stay in Netra; NICC consumes site × segment aggregates only (UU PDP).',
    criticality: 'important',
    classes: ['capacity'],
    fields: [
      { name: 'site_id, segment, date', type: 'key', description: 'Aggregation key' },
      { name: 'cnx_score', type: 'float', description: 'Mean CNX' },
      { name: 'subs', type: 'int', description: 'Subscribers in segment' },
    ],
  },
  {
    id: 'SRC-REV',
    name: 'Revenue per site catchment',
    domain: 'Customer and revenue',
    systems: 'Finance BI / revenue assurance',
    owner: 'Finance BI',
    grain: 'Site × month',
    refresh: 'Monthly (D+5)',
    latency: 'M-1',
    historyNeeded: '12 months',
    historyAvailable: '12 months, allocation method to agree',
    volume: '~60k rows / month',
    status: 'partial',
    integration: 'Netra batch connector (new)',
    pii: false,
    quality: 72,
    qualityNotes: 'Catchment allocation of subscriber revenue to sites is a modelling choice; agree method with Finance.',
    criticality: 'important',
    classes: ['all'],
    gap: 'Agree catchment revenue allocation with Finance; monthly load into Netra.',
    fields: [
      { name: 'site_id, month', type: 'key', description: 'Aggregation key' },
      { name: 'revenue_idr', type: 'int', description: 'Allocated monthly revenue' },
      { name: 'postpaid_share, enterprise_accounts', type: 'float, int', description: 'Mix' },
    ],
  },
  {
    id: 'SRC-DEVICE',
    name: 'Device capability (TAC)',
    domain: 'Customer and revenue',
    systems: 'EIR / device database, CDR aggregates',
    owner: 'CX Analytics',
    grain: 'Site × device capability × month',
    refresh: 'Monthly',
    latency: 'M-1',
    historyNeeded: '6 months',
    historyAvailable: 'Available, not aggregated by site',
    volume: 'Small after aggregation',
    status: 'partial',
    integration: 'Netra aggregate job (new)',
    pii: true,
    quality: 80,
    qualityNotes: 'Aggregate to site; no IMSI-level data leaves Netra.',
    criticality: 'enhancing',
    classes: ['capacity'],
    fields: [{ name: 'site_id, month, share_5g, share_lte_a', type: 'aggregate', description: 'Capable device share' }],
  },
  {
    id: 'SRC-RMS',
    name: 'Power telemetry (RMS / BMS)',
    domain: 'Power and energy',
    systems: 'Remote monitoring system, battery management systems',
    owner: 'Network Operations · Power / managed service partners',
    grain: 'Site × 15 min',
    refresh: 'Daily batch',
    latency: 'D-1',
    historyNeeded: '12 months',
    historyAvailable: 'Held by managed service partners; coverage ~55% of sites',
    volume: '~100 m readings / month',
    status: 'not_on_netra',
    integration: 'Partner API / SFTP into Netra (new)',
    pii: false,
    quality: 60,
    qualityNotes: 'Coverage uneven; older lead-acid sites have no BMS. Use alarm-derived proxies where telemetry is missing.',
    criticality: 'blocking',
    classes: ['power'],
    gap: 'Contract data-sharing clause with managed service partners; onboard RMS feed. Until then the power model runs on alarm proxies (lower recall).',
    fields: [
      { name: 'site_id, ts', type: 'key', description: 'Reading' },
      { name: 'battery_soh_pct / dod_pct', type: 'float', description: 'State of health, depth of discharge' },
      { name: 'rectifier_load_pct', type: 'float', description: 'Rectifier load' },
      { name: 'cabinet_temp_c', type: 'float', description: 'Cabinet temperature' },
      { name: 'mains_status', type: 'bool', description: 'Grid present' },
    ],
  },
  {
    id: 'SRC-FUEL',
    name: 'Genset fuel and run-hour logs',
    domain: 'Power and energy',
    systems: 'Fuel management / managed service reports',
    owner: 'Network Operations · Power',
    grain: 'Site × refuel / day',
    refresh: 'Weekly',
    latency: 'W-1',
    historyNeeded: '12 months',
    historyAvailable: 'Spreadsheets per region',
    volume: 'Small',
    status: 'not_on_netra',
    integration: 'Structured upload → Netra (new)',
    pii: false,
    quality: 55,
    qualityNotes: 'Manual logs; run hours derivable from RMS where present.',
    criticality: 'important',
    classes: ['power'],
    gap: 'Standard template and weekly upload; replace with RMS run hours where available.',
    fields: [{ name: 'site_id, date, run_hours, litres, tank_level_pct', type: 'record', description: 'Daily genset usage' }],
  },
  {
    id: 'SRC-PLN',
    name: 'Grid outage notifications (PLN)',
    domain: 'External',
    systems: 'PLN outage notices, site mains-failure alarms as proxy',
    owner: 'Network Operations · Power',
    grain: 'Feeder / area outage',
    refresh: 'Daily',
    latency: 'D-1',
    historyNeeded: '12 months',
    historyAvailable: 'Alarm proxy only',
    volume: 'Small',
    status: 'not_on_netra',
    integration: 'Derived from SRC-FM mains alarms; PLN B2B feed to explore',
    pii: false,
    quality: 65,
    qualityNotes: 'Mains-failure alarms are a reliable proxy for grid outages at site level.',
    criticality: 'enhancing',
    classes: ['power'],
    fields: [{ name: 'site_id, start, end', type: 'event', description: 'Mains failure window' }],
  },
  {
    id: 'SRC-TNMS',
    name: 'Transport NMS',
    domain: 'Transport',
    systems: 'Microwave and IP transport NMS (per vendor)',
    owner: 'Transport Engineering',
    grain: 'Link × 15 min; topology snapshot',
    refresh: 'Daily',
    latency: 'D-1',
    historyNeeded: '12 months',
    historyAvailable: 'Utilisation on Netra for core links only; MW RSL not on Netra',
    volume: '~40k links',
    status: 'partial',
    integration: 'Netra batch connector (extend to access links + RSL + topology)',
    pii: false,
    quality: 66,
    qualityNotes: 'Topology (which sites depend on which link) maintained manually; needed for dependent-site counts.',
    criticality: 'blocking',
    classes: ['transport'],
    gap: 'Onboard access-link utilisation, MW RSL / fade events and topology. Transport class stays advisory until then.',
    fields: [
      { name: 'link_id, from_site, to_site', type: 'key', description: 'Link and endpoints' },
      { name: 'util_p95_pct', type: 'float', description: 'P95 utilisation' },
      { name: 'rsl_dbm / fade_events', type: 'float / int', description: 'Microwave received signal level' },
      { name: 'protection', type: 'enum', description: 'none, 1+1, ring' },
    ],
  },
  {
    id: 'SRC-BMKG',
    name: 'Weather forecasts (BMKG)',
    domain: 'External',
    systems: 'BMKG open data / API',
    owner: 'DevX (integration) · Network Operations (use)',
    grain: 'Grid cell × day; dasarian outlook',
    refresh: 'Daily 06:00',
    latency: 'Forecast',
    historyNeeded: '24 months of forecasts + actuals',
    historyAvailable: 'Public archive',
    volume: 'Small',
    status: 'not_on_netra',
    integration: 'Public API → Netra (new)',
    pii: false,
    quality: 75,
    qualityNotes: 'Resolution coarse in Papua and Maluku.',
    criticality: 'blocking',
    classes: ['environmental', 'transport'],
    gap: 'Onboard BMKG forecasts and archive. Environmental class stays in shadow mode until then.',
    fields: [{ name: 'grid_id, date, rain_mm, wind_kmh, outlook_dasarian', type: 'record', description: 'Forecast' }],
  },
  {
    id: 'SRC-INARISK',
    name: 'Hazard maps (BNPB InaRISK) and DEM',
    domain: 'External',
    systems: 'BNPB InaRISK, national DEM',
    owner: 'DevX (integration)',
    grain: 'Raster / polygon, joined to site',
    refresh: 'Quarterly',
    latency: 'Static',
    historyNeeded: '5-year flood history',
    historyAvailable: 'Public',
    volume: 'One-off load',
    status: 'not_on_netra',
    integration: 'One-off geospatial join → Netra table',
    pii: false,
    quality: 78,
    qualityNotes: 'Join once per quarter; elevation fills the site-master gap.',
    criticality: 'important',
    classes: ['environmental'],
    fields: [{ name: 'site_id, flood_class, landslide_class, elevation_m, dist_water_m', type: 'record', description: 'Per-site hazard attributes' }],
  },
  {
    id: 'SRC-VENDOR',
    name: 'Vendor MTBF and hardware catalogue',
    domain: 'Supply chain',
    systems: 'OEM documentation (Ericsson, Nokia, Huawei, ZTE)',
    owner: 'Network Operations · RAN',
    grain: 'Unit type',
    refresh: 'Quarterly',
    latency: 'Static',
    historyNeeded: '—',
    historyAvailable: 'PDF documentation',
    volume: '~300 unit types',
    status: 'not_on_netra',
    integration: 'Curated reference table',
    pii: false,
    quality: 70,
    qualityNotes: 'Published MTBF optimistic; calibrate with IOH swap history.',
    criticality: 'enhancing',
    classes: ['ran_hardware'],
    fields: [{ name: 'unit_type, vendor, mtbf_years, end_of_support', type: 'record', description: 'Reference' }],
  },
  {
    id: 'SRC-SMARTCAPEX',
    name: 'Smart CapEx rankings',
    domain: 'Planning outputs',
    systems: 'Smart CapEx engine on Netra',
    owner: 'Network Planning',
    grain: 'Site × run',
    refresh: 'Daily on D-5 data',
    latency: 'D-5',
    historyNeeded: '6 months of runs',
    historyAvailable: '18 months',
    volume: '~60k rows / run',
    status: 'on_netra',
    integration: 'Netra table (existing); consumed as-is, no rework',
    pii: false,
    quality: 92,
    qualityNotes: 'Runs on D-5 data; NICC shows the age next to every classification.',
    criticality: 'blocking',
    classes: ['all'],
    fields: [
      { name: 'site_id, run_date', type: 'key', description: 'Ranking run' },
      { name: 'rank, score', type: 'int, float', description: 'Investment priority' },
      { name: 'capex_flag, rationale_codes', type: 'bool, string[]', description: 'CapEx vs non-CapEx and reasons' },
    ],
  },
  {
    id: 'SRC-ERP',
    name: 'ERP: price book, contracts, purchase orders',
    domain: 'Supply chain',
    systems: 'ERP (SAP, to confirm)',
    owner: 'Procurement',
    grain: 'SKU price, framework agreement, PO line',
    refresh: 'Daily',
    latency: 'D-1',
    historyNeeded: '12 months of POs',
    historyAvailable: 'In ERP',
    volume: '~40k PO lines / year',
    status: 'partial',
    integration: 'Read: Netra connector. Write: PO draft via ERP API or file drop (Phase 1 hand-off)',
    pii: false,
    quality: 85,
    qualityNotes: 'SKU codes differ from vendor catalogue codes; mapping table required.',
    criticality: 'blocking',
    classes: ['all'],
    gap: 'SKU mapping table; agree PO-draft interface (BAPI / IDoc / CSV drop) with ERP team.',
    fields: [
      { name: 'sku, unit_price_idr, valid_from', type: 'record', description: 'Price book' },
      { name: 'contract_id, vendor_id, ceiling_idr', type: 'record', description: 'Framework agreements' },
      { name: 'po_id, status, lines[]', type: 'record', description: 'Open POs' },
    ],
  },
  {
    id: 'SRC-WMS',
    name: 'Warehouse stock',
    domain: 'Supply chain',
    systems: 'Warehouse management (8 regional warehouses)',
    owner: 'Supply Chain',
    grain: 'Warehouse × SKU',
    refresh: 'Daily',
    latency: 'D-1',
    historyNeeded: 'Current + reservations',
    historyAvailable: 'Current',
    volume: '~8 × 2,000 SKUs',
    status: 'partial',
    integration: 'Netra batch connector (new)',
    pii: false,
    quality: 77,
    qualityNotes: 'Reservations tracked in spreadsheets for some regions.',
    criticality: 'blocking',
    classes: ['all'],
    gap: 'Daily stock and reservation extract; reservation API for plan drafts.',
    fields: [{ name: 'warehouse_id, sku, on_hand, reserved, reorder_point, lead_days', type: 'record', description: 'Stock position' }],
  },
  {
    id: 'SRC-VPORTAL',
    name: 'Vendor portal: capacity and SLA',
    domain: 'Supply chain',
    systems: 'Vendor / partner portal (to confirm)',
    owner: 'Deployment PMO',
    grain: 'Vendor × region × month',
    refresh: 'Weekly',
    latency: 'W-1',
    historyNeeded: '12 months SLA history',
    historyAvailable: 'PMO trackers',
    volume: 'Small',
    status: 'not_on_netra',
    integration: 'Portal API or structured upload (new); allocation proposal sent as a draft',
    pii: false,
    quality: 60,
    qualityNotes: 'Capacity declared by vendors; SLA history from PMO trackers.',
    criticality: 'important',
    classes: ['all'],
    gap: 'Weekly capacity and SLA feed; read-only in Phase 1.',
    fields: [{ name: 'vendor_id, region, capacity_sites_month, sla_pct, active_allocations', type: 'record', description: 'Capacity and performance' }],
  },
  {
    id: 'SRC-TOWERCO',
    name: 'Tower company loading and access',
    domain: 'Supply chain',
    systems: 'Mitratel, Protelindo, TBIG, EdgePoint portals and lease DB',
    owner: 'Deployment · Tower relations',
    grain: 'Site lease, loading allowance',
    refresh: 'Monthly',
    latency: 'M-1',
    historyNeeded: 'Current leases',
    historyAvailable: 'Lease DB; loading allowance per site partly on paper',
    volume: '~45k leases',
    status: 'not_on_netra',
    integration: 'Lease DB extract; access requests drafted as documents in Phase 1',
    pii: false,
    quality: 58,
    qualityNotes: 'Loading allowance is the main unknown for sector-add feasibility.',
    criticality: 'important',
    classes: ['capacity', 'transport'],
    gap: 'Lease DB extract with loading allowance; standard access-request template per tower company.',
    fields: [{ name: 'site_id, tower_company, lease_end, loading_allowance_kg, access_sla_days', type: 'record', description: 'Lease and loading' }],
  },
  {
    id: 'SRC-SPECTRUM',
    name: 'Band plan and spectrum holdings',
    domain: 'Inventory and config',
    systems: 'Spectrum management (Planning)',
    owner: 'Network Planning · Spectrum',
    grain: 'Band × region',
    refresh: 'Quarterly',
    latency: 'Static',
    historyNeeded: 'Current',
    historyAvailable: 'Available',
    volume: 'Small',
    status: 'partial',
    integration: 'Reference table on Netra (new)',
    pii: false,
    quality: 85,
    qualityNotes: 'Needed to propose refarming as the zero-CapEx first rung.',
    criticality: 'enhancing',
    classes: ['capacity'],
    fields: [{ name: 'region, band, bandwidth_mhz, technology_split', type: 'record', description: 'Holdings and use' }],
  },
  {
    id: 'SRC-EVENTS',
    name: 'Events calendar',
    domain: 'External',
    systems: 'Regional marketing and ops calendars',
    owner: 'Regional Network Managers',
    grain: 'Event × location × date',
    refresh: 'Weekly',
    latency: 'Forward-looking',
    historyNeeded: '12 months',
    historyAvailable: 'Scattered',
    volume: 'Small',
    status: 'not_on_netra',
    integration: 'Structured form in NICC → Netra',
    pii: false,
    quality: 50,
    qualityNotes: 'Concerts, Lebaran mudik, campus terms drive capacity spikes.',
    criticality: 'enhancing',
    classes: ['capacity'],
    fields: [{ name: 'event, district_code, start, end, expected_crowd', type: 'record', description: 'Planned event' }],
  },
]

export const STATUS_LABEL: Record<NetraStatus, string> = {
  on_netra: 'On Netra',
  partial: 'Partial',
  not_on_netra: 'Not on Netra',
}
